#-------------------------------
# General Site Settings

#title: Jonathan's Photography
#description: Designer // Photographer
email: jtsodik@gmail.com
header-name: Jonathan's<br>Photography

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "Jonathan's Photography Portfolio."
  rel-author: 'http://tjonathan.github.io/Portfolio/'
  rel-publisher: 'http://tjonathan.github.io/Portfolio/'

#-------------------------------
# Google Analytics Section

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Jonathan specializes in making things happen.** He is always willing to learn from the best and share his knowledge. His different point of view makes his work even more unique.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '6'}
- {name: Photographing, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Swan double trouble, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Bird love, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Koala hanging, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Catch me if you can, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: BMX, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Orange flowers, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Nowhere, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Sunset, folder: 'proj-8', file: 'work/proj-8.html'}



#-------------------------------
# Contact Section

social:
- {icon: 'facebook', link: 'http://facebook.com/jeka.insanity'}
- {icon: 'github', link: 'https://github.com/TJonathan'}
- {icon: 'instagram', link: 'http://instagram.com/jeka_tso'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
